apiVersion: v1
kind: deployment
metadata: 
  name: khushi-deployment
  namespace: khushi
spec: 
  replicas: 4
  selector: 
    matchlabels: 
      app: khushi-app
  template: 
    metadata: 
      labels: 
        app: khushi-app
    spec: 
      containers: 
        - name: khushi-container
          image: nginx:latest
          ports: 
            - containerPort: 80
