apiVersion: v1
kind: Service
metadata:
  name: khushi-service
spec:
  selector:
    app: khushi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

  # clusterIp
  apiVersion: v1
kind: service
metadta:
  name: khushi-service
  namespace: khushi
spec:
  selector:
  matchLables:
    app: khushi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

  # loadbaalncer
  apiVersion: v1
kind: service
metadta:
  name: khushi-service
  namespace: khushi
spec:
  selector:
  matchLables:
    app: khushi-app
  port:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

